package com.sistema.model;

public enum TipoTrabajoSincronizacion {
    SINCRONIZACION_CANALES,
    PUBLICACION_SELECCIONADA,
    IMPORTACION_COMPLETA,
    PREPARACION_IMPORTACION,
    IMPORTACION_SELECCIONADA,
    SINCRONIZACION_SELECCIONADA
}
